export const FOOD_LIBRARY = [
  {
    id: "chicken-breast",
    name: "Chicken Breast",
    category: "protein",
    servingSize: "4 oz cooked",
    calories: 187,
    protein: 35,
    carbs: 0,
    fat: 4,
    source: "Repeated across Tasty Shreds meal-prep PDFs",
  },
  {
    id: "nonfat-greek-yogurt",
    name: "Nonfat Greek Yogurt",
    category: "protein",
    servingSize: "170 g",
    calories: 100,
    protein: 18,
    carbs: 6,
    fat: 0,
    source: "Repeated across Frozen Food Favorites and Tasty Shreds PDFs",
  },
  {
    id: "low-fat-cottage-cheese",
    name: "Low-Fat Cottage Cheese",
    category: "protein",
    servingSize: "1/2 cup",
    calories: 90,
    protein: 13,
    carbs: 4,
    fat: 2,
    source: "Repeated across Tasty Shreds PDFs",
  },
  {
    id: "egg-whites",
    name: "Egg Whites",
    category: "protein",
    servingSize: "1 cup",
    calories: 126,
    protein: 26,
    carbs: 2,
    fat: 0,
    source: "Repeated across Tasty Shreds PDFs",
  },
  {
    id: "whole-eggs",
    name: "Whole Eggs",
    category: "protein",
    servingSize: "2 large eggs",
    calories: 140,
    protein: 12,
    carbs: 1,
    fat: 10,
    source: "Repeated across Tasty Shreds PDFs",
  },
  {
    id: "ground-chicken",
    name: "Ground Chicken",
    category: "protein",
    servingSize: "4 oz cooked",
    calories: 170,
    protein: 22,
    carbs: 0,
    fat: 8,
    source: "Repeated across Tasty Shreds PDFs",
  },
  {
    id: "lean-ground-beef",
    name: "96/4 Lean Ground Beef",
    category: "protein",
    servingSize: "4 oz cooked",
    calories: 170,
    protein: 24,
    carbs: 0,
    fat: 8,
    source: "Repeated across Frozen Food Favorites and Tasty Shreds PDFs",
  },
  {
    id: "shrimp",
    name: "Shrimp",
    category: "protein",
    servingSize: "4 oz cooked",
    calories: 120,
    protein: 23,
    carbs: 1,
    fat: 2,
    source: "Repeated across Tasty Shreds PDFs",
  },
  {
    id: "salmon",
    name: "Salmon",
    category: "protein",
    servingSize: "4 oz cooked",
    calories: 233,
    protein: 25,
    carbs: 0,
    fat: 14,
    source: "Repeated across Tasty Shreds PDFs",
  },
  {
    id: "jasmine-rice",
    name: "Jasmine Rice",
    category: "carb",
    servingSize: "1 cup cooked",
    calories: 205,
    protein: 4,
    carbs: 45,
    fat: 0,
    source: "Repeated across Tasty Shreds PDFs",
  },
  {
    id: "russet-potato",
    name: "Potato",
    category: "carb",
    servingSize: "250 g baked",
    calories: 220,
    protein: 5,
    carbs: 50,
    fat: 0,
    source: "Repeated across Frozen Food Favorites and Tasty Shreds PDFs",
  },
  {
    id: "sweet-potato",
    name: "Sweet Potato",
    category: "carb",
    servingSize: "200 g baked",
    calories: 180,
    protein: 4,
    carbs: 41,
    fat: 0,
    source: "Repeated across Tasty Shreds PDFs",
  },
  {
    id: "old-fashioned-oats",
    name: "Old-Fashioned Oats",
    category: "carb",
    servingSize: "1/2 cup dry",
    calories: 150,
    protein: 5,
    carbs: 27,
    fat: 3,
    source: "Repeated across Tasty Shreds PDFs",
  },
  {
    id: "banana",
    name: "Banana",
    category: "carb",
    servingSize: "1 medium",
    calories: 105,
    protein: 1,
    carbs: 27,
    fat: 0,
    source: "Repeated across Tasty Shreds PDFs",
  },
  {
    id: "zero-carb-tortilla",
    name: "Low-Calorie Tortilla",
    category: "carb",
    servingSize: "1 tortilla",
    calories: 25,
    protein: 2,
    carbs: 7,
    fat: 1,
    source: "Repeated across Frozen Food Favorites and Tasty Shreds PDFs",
  },
  {
    id: "banza-pasta",
    name: "Banza Pasta",
    category: "carb",
    servingSize: "2 oz dry",
    calories: 190,
    protein: 11,
    carbs: 35,
    fat: 3,
    source: "Repeated across Tasty Shreds PDFs",
  },
  {
    id: "avocado",
    name: "Avocado",
    category: "fat",
    servingSize: "1/2 avocado",
    calories: 120,
    protein: 2,
    carbs: 6,
    fat: 11,
    source: "Repeated across Frozen Food Favorites and Tasty Shreds PDFs",
  },
  {
    id: "olive-oil",
    name: "Olive Oil",
    category: "fat",
    servingSize: "1 tbsp",
    calories: 120,
    protein: 0,
    carbs: 0,
    fat: 14,
    source: "Repeated across Tasty Shreds PDFs",
  },
  {
    id: "reduced-fat-cheddar",
    name: "Reduced-Fat Cheddar",
    category: "fat",
    servingSize: "28 g",
    calories: 80,
    protein: 7,
    carbs: 1,
    fat: 6,
    source: "Repeated across Frozen Food Favorites and Tasty Shreds PDFs",
  },
  {
    id: "turkey-bacon",
    name: "Turkey Bacon",
    category: "fat",
    servingSize: "2 slices",
    calories: 70,
    protein: 5,
    carbs: 0,
    fat: 5,
    source: "Repeated across Tasty Shreds PDFs",
  },
];
