export const FOOD_LIBRARY = [
  {
    id: "chicken-breast",
    name: "Chicken Breast",
    category: "protein",
    servingSize: "4 oz cooked",
    baseAmount: 4,
    baseUnit: "oz",
    servingNote: "cooked",
    isScalable: true,
    calories: 187,
    protein: 35,
    carbs: 0,
    fat: 4,
  },
  {
    id: "nonfat-greek-yogurt",
    name: "Nonfat Greek Yogurt",
    category: "protein",
    servingSize: "170 g",
    baseAmount: 170,
    baseUnit: "g",
    isScalable: true,
    calories: 100,
    protein: 18,
    carbs: 6,
    fat: 0,
  },
  {
    id: "low-fat-cottage-cheese",
    name: "Low-Fat Cottage Cheese",
    category: "protein",
    servingSize: "1/2 cup",
    baseAmount: 0.5,
    baseUnit: "cup",
    isScalable: true,
    calories: 90,
    protein: 13,
    carbs: 4,
    fat: 2,
  },
  {
    id: "egg-whites",
    name: "Egg Whites",
    category: "protein",
    servingSize: "1 cup",
    baseAmount: 1,
    baseUnit: "cup",
    isScalable: true,
    calories: 126,
    protein: 26,
    carbs: 2,
    fat: 0,
  },
  {
    id: "whole-eggs",
    name: "Whole Eggs",
    category: "protein",
    servingSize: "2 large eggs",
    baseAmount: 2,
    baseUnit: "eggs",
    servingNote: "large",
    isScalable: true,
    calories: 140,
    protein: 12,
    carbs: 1,
    fat: 10,
  },
  {
    id: "ground-chicken",
    name: "Ground Chicken",
    category: "protein",
    servingSize: "4 oz cooked",
    baseAmount: 4,
    baseUnit: "oz",
    servingNote: "cooked",
    isScalable: true,
    calories: 170,
    protein: 22,
    carbs: 0,
    fat: 8,
  },
  {
    id: "lean-ground-beef",
    name: "96/4 Lean Ground Beef",
    category: "protein",
    servingSize: "4 oz cooked",
    baseAmount: 4,
    baseUnit: "oz",
    servingNote: "cooked",
    isScalable: true,
    calories: 170,
    protein: 24,
    carbs: 0,
    fat: 8,
  },
  {
    id: "shrimp",
    name: "Shrimp",
    category: "protein",
    servingSize: "4 oz cooked",
    baseAmount: 4,
    baseUnit: "oz",
    servingNote: "cooked",
    isScalable: true,
    calories: 120,
    protein: 23,
    carbs: 1,
    fat: 2,
  },
  {
    id: "salmon",
    name: "Salmon",
    category: "protein",
    servingSize: "4 oz cooked",
    baseAmount: 4,
    baseUnit: "oz",
    servingNote: "cooked",
    isScalable: true,
    calories: 233,
    protein: 25,
    carbs: 0,
    fat: 14,
  },
  {
    id: "jasmine-rice",
    name: "Jasmine Rice",
    category: "carb",
    servingSize: "1 cup cooked",
    baseAmount: 1,
    baseUnit: "cup",
    servingNote: "cooked",
    isScalable: true,
    calories: 205,
    protein: 4,
    carbs: 45,
    fat: 0,
  },
  {
    id: "russet-potato",
    name: "Potato",
    category: "carb",
    servingSize: "250 g baked",
    baseAmount: 250,
    baseUnit: "g",
    servingNote: "baked",
    isScalable: true,
    calories: 220,
    protein: 5,
    carbs: 50,
    fat: 0,
  },
  {
    id: "sweet-potato",
    name: "Sweet Potato",
    category: "carb",
    servingSize: "200 g baked",
    baseAmount: 200,
    baseUnit: "g",
    servingNote: "baked",
    isScalable: true,
    calories: 180,
    protein: 4,
    carbs: 41,
    fat: 0,
  },
  {
    id: "old-fashioned-oats",
    name: "Old-Fashioned Oats",
    category: "carb",
    servingSize: "1/2 cup dry",
    baseAmount: 0.5,
    baseUnit: "cup",
    servingNote: "dry",
    isScalable: true,
    calories: 150,
    protein: 5,
    carbs: 27,
    fat: 3,
  },
  {
    id: "banana",
    name: "Banana",
    category: "carb",
    servingSize: "1 medium",
    baseAmount: 1,
    baseUnit: "banana",
    servingNote: "medium",
    isScalable: true,
    calories: 105,
    protein: 1,
    carbs: 27,
    fat: 0,
  },
  {
    id: "zero-carb-tortilla",
    name: "Low-Calorie Tortilla",
    category: "carb",
    servingSize: "1 tortilla",
    baseAmount: 1,
    baseUnit: "tortilla",
    isScalable: true,
    calories: 25,
    protein: 2,
    carbs: 7,
    fat: 1,
  },
  {
    id: "banza-pasta",
    name: "Banza Pasta",
    category: "carb",
    servingSize: "2 oz dry",
    baseAmount: 2,
    baseUnit: "oz",
    servingNote: "dry",
    isScalable: true,
    calories: 190,
    protein: 11,
    carbs: 35,
    fat: 3,
  },
  {
    id: "avocado",
    name: "Avocado",
    category: "fat",
    servingSize: "1/2 avocado",
    baseAmount: 0.5,
    baseUnit: "avocado",
    isScalable: true,
    calories: 120,
    protein: 2,
    carbs: 6,
    fat: 11,
  },
  {
    id: "olive-oil",
    name: "Olive Oil",
    category: "fat",
    servingSize: "1 tbsp",
    baseAmount: 1,
    baseUnit: "tbsp",
    isScalable: true,
    calories: 120,
    protein: 0,
    carbs: 0,
    fat: 14,
  },
  {
    id: "reduced-fat-cheddar",
    name: "Reduced-Fat Cheddar",
    category: "fat",
    servingSize: "28 g",
    baseAmount: 28,
    baseUnit: "g",
    isScalable: true,
    calories: 80,
    protein: 7,
    carbs: 1,
    fat: 6,
  },
  {
    id: "turkey-bacon",
    name: "Turkey Bacon",
    category: "fat",
    servingSize: "2 slices",
    baseAmount: 2,
    baseUnit: "slices",
    isScalable: true,
    calories: 70,
    protein: 5,
    carbs: 0,
    fat: 5,
  },
];
