export const FOOD_LIBRARY = [
  {
    id: "chicken-breast",
    name: "Chicken Breast",
    category: "protein",
    servingSize: "4 oz cooked",
    baseAmount: 4,
    baseUnit: "oz",
    servingNote: "cooked",
    isScalable: true,
    calories: 187,
    protein: 35,
    carbs: 0,
    fat: 4,
  },
  {
    id: "nonfat-greek-yogurt",
    name: "Nonfat Greek Yogurt",
    category: "protein",
    servingSize: "170 g",
    baseAmount: 170,
    baseUnit: "g",
    isScalable: true,
    calories: 100,
    protein: 18,
    carbs: 6,
    fat: 0,
  },
  {
    id: "low-fat-cottage-cheese",
    name: "Low-Fat Cottage Cheese",
    category: "protein",
    servingSize: "1/2 cup",
    baseAmount: 0.5,
    baseUnit: "cup",
    isScalable: true,
    calories: 90,
    protein: 13,
    carbs: 4,
    fat: 2,
  },
  {
    id: "2-percent-greek-yogurt",
    name: "2% Greek Yogurt",
    category: "protein",
    servingSize: "170 g",
    baseAmount: 170,
    baseUnit: "g",
    isScalable: true,
    calories: 130,
    protein: 15,
    carbs: 6,
    fat: 4,
  },
  {
    id: "2-percent-cottage-cheese",
    name: "2% Cottage Cheese",
    category: "protein",
    servingSize: "1/2 cup",
    baseAmount: 0.5,
    baseUnit: "cup",
    isScalable: true,
    calories: 90,
    protein: 12,
    carbs: 5,
    fat: 2.5,
  },
  {
    id: "egg-whites",
    name: "Egg Whites",
    category: "protein",
    servingSize: "1 cup",
    baseAmount: 1,
    baseUnit: "cup",
    isScalable: true,
    calories: 126,
    protein: 26,
    carbs: 2,
    fat: 0,
  },
  {
    id: "whole-eggs",
    name: "Whole Eggs",
    category: "protein",
    servingSize: "1 large egg",
    baseAmount: 1,
    baseUnit: "eggs",
    servingNote: "large",
    isScalable: true,
    calories: 70,
    protein: 6,
    carbs: 0.5,
    fat: 5,
  },
  {
    id: "ground-chicken",
    name: "Ground Chicken",
    category: "protein",
    servingSize: "4 oz cooked",
    baseAmount: 4,
    baseUnit: "oz",
    servingNote: "cooked",
    isScalable: true,
    calories: 170,
    protein: 22,
    carbs: 0,
    fat: 8,
  },
  {
    id: "lean-ground-beef",
    name: "96/4 Lean Ground Beef",
    category: "protein",
    servingSize: "4 oz cooked",
    baseAmount: 4,
    baseUnit: "oz",
    servingNote: "cooked",
    isScalable: true,
    calories: 170,
    protein: 24,
    carbs: 0,
    fat: 8,
  },
  {
    id: "shrimp",
    name: "Shrimp",
    category: "protein",
    servingSize: "4 oz cooked",
    baseAmount: 4,
    baseUnit: "oz",
    servingNote: "cooked",
    isScalable: true,
    calories: 120,
    protein: 23,
    carbs: 1,
    fat: 2,
  },
  {
    id: "salmon",
    name: "Salmon",
    category: "protein",
    servingSize: "4 oz cooked",
    baseAmount: 4,
    baseUnit: "oz",
    servingNote: "cooked",
    isScalable: true,
    calories: 233,
    protein: 25,
    carbs: 0,
    fat: 14,
  },
  {
    id: "jasmine-rice",
    name: "Jasmine Rice",
    category: "carb",
    servingSize: "1 cup cooked",
    baseAmount: 1,
    baseUnit: "cup",
    servingNote: "cooked",
    isScalable: true,
    calories: 205,
    protein: 4,
    carbs: 45,
    fat: 0,
  },
  {
    id: "russet-potato",
    name: "Potato",
    category: "carb",
    servingSize: "250 g baked",
    baseAmount: 250,
    baseUnit: "g",
    servingNote: "baked",
    isScalable: true,
    calories: 220,
    protein: 5,
    carbs: 50,
    fat: 0,
  },
  {
    id: "sweet-potato",
    name: "Sweet Potato",
    category: "carb",
    servingSize: "200 g baked",
    baseAmount: 200,
    baseUnit: "g",
    servingNote: "baked",
    isScalable: true,
    calories: 180,
    protein: 4,
    carbs: 41,
    fat: 0,
  },
  {
    id: "old-fashioned-oats",
    name: "Old-Fashioned Oats",
    category: "carb",
    servingSize: "1/2 cup dry",
    baseAmount: 0.5,
    baseUnit: "cup",
    servingNote: "dry",
    isScalable: true,
    calories: 150,
    protein: 5,
    carbs: 27,
    fat: 3,
  },
  {
    id: "banana",
    name: "Banana",
    category: "carb",
    servingSize: "1 medium",
    baseAmount: 1,
    baseUnit: "banana",
    servingNote: "medium",
    isScalable: true,
    calories: 105,
    protein: 1,
    carbs: 27,
    fat: 0,
  },
  {
    id: "zero-carb-tortilla",
    name: "Low-Calorie Tortilla",
    category: "carb",
    servingSize: "1 tortilla",
    baseAmount: 1,
    baseUnit: "tortilla",
    isScalable: true,
    calories: 25,
    protein: 2,
    carbs: 7,
    fat: 1,
  },
  {
    id: "banza-pasta",
    name: "Banza Pasta",
    category: "carb",
    servingSize: "2 oz dry",
    baseAmount: 2,
    baseUnit: "oz",
    servingNote: "dry",
    isScalable: true,
    calories: 190,
    protein: 11,
    carbs: 35,
    fat: 3,
  },
  {
    id: "avocado",
    name: "Avocado",
    category: "fat",
    servingSize: "1/2 avocado",
    baseAmount: 0.5,
    baseUnit: "avocado",
    isScalable: true,
    calories: 120,
    protein: 2,
    carbs: 6,
    fat: 11,
  },
  {
    id: "olive-oil",
    name: "Olive Oil",
    category: "fat",
    servingSize: "1 tbsp",
    baseAmount: 1,
    baseUnit: "tbsp",
    isScalable: true,
    calories: 120,
    protein: 0,
    carbs: 0,
    fat: 14,
  },
  {
    id: "avocado-oil",
    name: "Avocado Oil",
    category: "fat",
    servingSize: "1 tbsp",
    baseAmount: 1,
    baseUnit: "tbsp",
    isScalable: true,
    calories: 124,
    protein: 0,
    carbs: 0,
    fat: 14,
  },
  {
    id: "peanut-butter",
    name: "Peanut Butter",
    category: "fat",
    servingSize: "1 tbsp",
    baseAmount: 1,
    baseUnit: "tbsp",
    isScalable: true,
    calories: 95,
    protein: 4,
    carbs: 3,
    fat: 8,
  },
  {
    id: "almond-butter",
    name: "Almond Butter",
    category: "fat",
    servingSize: "1 tbsp",
    baseAmount: 1,
    baseUnit: "tbsp",
    isScalable: true,
    calories: 98,
    protein: 3.5,
    carbs: 3,
    fat: 9,
  },
  {
    id: "almonds",
    name: "Almonds",
    category: "fat",
    servingSize: "28 g",
    baseAmount: 28,
    baseUnit: "g",
    isScalable: true,
    calories: 164,
    protein: 6,
    carbs: 6,
    fat: 14,
  },
  {
    id: "walnuts",
    name: "Walnuts",
    category: "fat",
    servingSize: "28 g",
    baseAmount: 28,
    baseUnit: "g",
    isScalable: true,
    calories: 185,
    protein: 4,
    carbs: 4,
    fat: 18,
  },
  {
    id: "pistachios",
    name: "Pistachios",
    category: "fat",
    servingSize: "28 g",
    baseAmount: 28,
    baseUnit: "g",
    isScalable: true,
    calories: 160,
    protein: 6,
    carbs: 8,
    fat: 13,
  },
  {
    id: "chia-seeds",
    name: "Chia Seeds",
    category: "fat",
    servingSize: "1 tbsp",
    baseAmount: 1,
    baseUnit: "tbsp",
    isScalable: true,
    calories: 58,
    protein: 2,
    carbs: 5,
    fat: 4,
  },
  {
    id: "flaxseed",
    name: "Ground Flaxseed",
    category: "fat",
    servingSize: "1 tbsp",
    baseAmount: 1,
    baseUnit: "tbsp",
    isScalable: true,
    calories: 37,
    protein: 1.3,
    carbs: 2,
    fat: 3,
  },
  {
    id: "reduced-fat-cheddar",
    name: "Reduced-Fat Cheddar",
    category: "fat",
    servingSize: "28 g",
    baseAmount: 28,
    baseUnit: "g",
    isScalable: true,
    calories: 80,
    protein: 7,
    carbs: 1,
    fat: 6,
  },
  {
    id: "part-skim-mozzarella",
    name: "Part-Skim Mozzarella",
    category: "protein",
    servingSize: "28 g",
    baseAmount: 28,
    baseUnit: "g",
    isScalable: true,
    calories: 72,
    protein: 7,
    carbs: 1,
    fat: 4.5,
  },
  {
    id: "string-cheese",
    name: "String Cheese",
    category: "protein",
    servingSize: "1 stick",
    baseAmount: 1,
    baseUnit: "stick",
    isScalable: true,
    calories: 80,
    protein: 7,
    carbs: 1,
    fat: 6,
  },
  {
    id: "parmesan",
    name: "Parmesan",
    category: "fat",
    servingSize: "2 tbsp",
    baseAmount: 2,
    baseUnit: "tbsp",
    isScalable: true,
    calories: 42,
    protein: 4,
    carbs: 0,
    fat: 3,
  },
  {
    id: "skim-milk",
    name: "Skim Milk",
    category: "carb",
    servingSize: "1 cup",
    baseAmount: 1,
    baseUnit: "cup",
    isScalable: true,
    calories: 83,
    protein: 8,
    carbs: 12,
    fat: 0,
  },
  {
    id: "2-percent-milk",
    name: "2% Milk",
    category: "carb",
    servingSize: "1 cup",
    baseAmount: 1,
    baseUnit: "cup",
    isScalable: true,
    calories: 122,
    protein: 8,
    carbs: 12,
    fat: 5,
  },
  {
    id: "unsweetened-almond-milk",
    name: "Unsweetened Almond Milk",
    category: "fat",
    servingSize: "1 cup",
    baseAmount: 1,
    baseUnit: "cup",
    isScalable: true,
    calories: 30,
    protein: 1,
    carbs: 1,
    fat: 2.5,
  },
  {
    id: "red-potato",
    name: "Red Potato",
    category: "carb",
    servingSize: "250 g baked",
    baseAmount: 250,
    baseUnit: "g",
    servingNote: "baked",
    isScalable: true,
    calories: 218,
    protein: 5,
    carbs: 49,
    fat: 0,
  },
  {
    id: "black-beans",
    name: "Black Beans",
    category: "carb",
    servingSize: "1/2 cup cooked",
    baseAmount: 0.5,
    baseUnit: "cup",
    servingNote: "cooked",
    isScalable: true,
    calories: 114,
    protein: 8,
    carbs: 20,
    fat: 0.5,
  },
  {
    id: "chickpeas",
    name: "Chickpeas",
    category: "carb",
    servingSize: "1/2 cup cooked",
    baseAmount: 0.5,
    baseUnit: "cup",
    servingNote: "cooked",
    isScalable: true,
    calories: 135,
    protein: 7,
    carbs: 22,
    fat: 2,
  },
  {
    id: "quinoa",
    name: "Quinoa",
    category: "carb",
    servingSize: "1 cup cooked",
    baseAmount: 1,
    baseUnit: "cup",
    servingNote: "cooked",
    isScalable: true,
    calories: 222,
    protein: 8,
    carbs: 39,
    fat: 3.5,
  },
  {
    id: "blueberries",
    name: "Blueberries",
    category: "carb",
    servingSize: "1 cup",
    baseAmount: 1,
    baseUnit: "cup",
    isScalable: true,
    calories: 84,
    protein: 1,
    carbs: 21,
    fat: 0.5,
  },
  {
    id: "strawberries",
    name: "Strawberries",
    category: "carb",
    servingSize: "1 cup",
    baseAmount: 1,
    baseUnit: "cup",
    isScalable: true,
    calories: 49,
    protein: 1,
    carbs: 12,
    fat: 0.5,
  },
  {
    id: "broccoli",
    name: "Broccoli",
    category: "carb",
    servingSize: "1 cup cooked",
    baseAmount: 1,
    baseUnit: "cup",
    servingNote: "cooked",
    isScalable: true,
    calories: 55,
    protein: 4,
    carbs: 11,
    fat: 0.5,
  },
  {
    id: "spinach",
    name: "Spinach",
    category: "carb",
    servingSize: "1 cup cooked",
    baseAmount: 1,
    baseUnit: "cup",
    servingNote: "cooked",
    isScalable: true,
    calories: 41,
    protein: 5,
    carbs: 7,
    fat: 0.5,
  },
  {
    id: "turkey-bacon",
    name: "Turkey Bacon",
    category: "fat",
    servingSize: "2 slices",
    baseAmount: 2,
    baseUnit: "slices",
    isScalable: true,
    calories: 70,
    protein: 5,
    carbs: 0,
    fat: 5,
  },
  {
    id: "optavia-creamy-vanilla-shake",
    name: "Creamy Vanilla Shake",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 sachet (32 g)",
    baseAmount: 1,
    baseUnit: "sachet",
    isScalable: true,
    calories: 110,
    protein: 14,
    carbs: 13,
    fat: 0.5,
  },
  {
    id: "optavia-caramel-delight-crisp-bar",
    name: "Caramel Delight Crisp Bar",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 bar (32 g)",
    baseAmount: 1,
    baseUnit: "bar",
    isScalable: true,
    calories: 110,
    protein: 11,
    carbs: 13,
    fat: 3.5,
  },
  {
    id: "optavia-decadent-chocolate-brownie",
    name: "Decadent Chocolate Brownie",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 sachet (31 g)",
    baseAmount: 1,
    baseUnit: "sachet",
    isScalable: true,
    calories: 110,
    protein: 11,
    carbs: 15,
    fat: 2,
  },
  {
    id: "optavia-roasted-garlic-mashed-potatoes",
    name: "Roasted Garlic Mashed Potatoes",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 sachet (32 g)",
    baseAmount: 1,
    baseUnit: "sachet",
    isScalable: true,
    calories: 100,
    protein: 11,
    carbs: 15,
    fat: 1,
  },
  {
    id: "optavia-cheesy-buttermilk-cheddar-mac",
    name: "Cheesy Buttermilk Cheddar Mac",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 sachet (33 g)",
    baseAmount: 1,
    baseUnit: "sachet",
    isScalable: true,
    calories: 110,
    protein: 11,
    carbs: 15,
    fat: 2,
  },
  {
    id: "optavia-mocha-shake",
    name: "Mocha Shake",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 sachet (32 g)",
    baseAmount: 1,
    baseUnit: "sachet",
    isScalable: true,
    calories: 100,
    protein: 14,
    carbs: 13,
    fat: 1,
  },
  {
    id: "optavia-creamy-chocolate-shake",
    name: "Creamy Chocolate Shake",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 sachet (32 g)",
    baseAmount: 1,
    baseUnit: "sachet",
    isScalable: true,
    calories: 100,
    protein: 14,
    carbs: 12,
    fat: 1,
  },
  {
    id: "optavia-strawberry-delight-shake",
    name: "Strawberry Delight Shake",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 sachet (31 g)",
    baseAmount: 1,
    baseUnit: "sachet",
    isScalable: true,
    calories: 100,
    protein: 14,
    carbs: 13,
    fat: 0.5,
  },
  {
    id: "optavia-caramel-macchiato-shake",
    name: "Caramel Macchiato Shake",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 sachet (30 g)",
    baseAmount: 1,
    baseUnit: "sachet",
    isScalable: true,
    calories: 100,
    protein: 12,
    carbs: 14,
    fat: 1,
  },
  {
    id: "optavia-peanut-butter-shake",
    name: "Peanut Butter Shake",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 sachet (30 g)",
    baseAmount: 1,
    baseUnit: "sachet",
    isScalable: true,
    calories: 110,
    protein: 12,
    carbs: 12,
    fat: 2.5,
  },
  {
    id: "optavia-cookie-dough-bar",
    name: "Cookie Dough Bar",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 bar (36 g)",
    baseAmount: 1,
    baseUnit: "bar",
    isScalable: true,
    calories: 110,
    protein: 11,
    carbs: 15,
    fat: 3,
  },
  {
    id: "optavia-lemon-tart-crisp-bar",
    name: "Lemon Tart Crisp Bar",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 bar (32 g)",
    baseAmount: 1,
    baseUnit: "bar",
    isScalable: true,
    calories: 110,
    protein: 11,
    carbs: 13,
    fat: 3.5,
  },
  {
    id: "optavia-apple-cinnamon-spiced-oatmeal",
    name: "Apple & Cinnamon Spiced Oatmeal",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 sachet (32 g)",
    baseAmount: 1,
    baseUnit: "sachet",
    isScalable: true,
    calories: 110,
    protein: 11,
    carbs: 15,
    fat: 1.5,
  },
  {
    id: "optavia-homestyle-chick-noodle-soup",
    name: "Homestyle Chick'n Noodle Soup",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 sachet (31 g)",
    baseAmount: 1,
    baseUnit: "sachet",
    isScalable: true,
    calories: 110,
    protein: 12,
    carbs: 13,
    fat: 2,
  },
  {
    id: "optavia-sour-cream-chive-mashed-potatoes",
    name: "Sour Cream & Chive Mashed Potatoes",
    brand: "OPTAVIA",
    allowedEmails: ["jennica.perkins@gmail.com"],
    category: "protein",
    servingSize: "1 sachet (32 g)",
    baseAmount: 1,
    baseUnit: "sachet",
    isScalable: true,
    calories: 100,
    protein: 11,
    carbs: 15,
    fat: 0.5,
  },
];
